#!/bin/bash

set -x
set -e

if [ "$EUID" -ne 0 ]
then
  echo "Please run as root"
  exit 1
fi

echo "Installing packages"
which aptitude || apt-get install aptitude
aptitude update && aptitude install -y vim git ruby ruby-dev build-essential \
  mysql-server libmysqlclient-dev \
  nodejs nodejs-legacy \
  augeas-tools etckeeper

gem install bundler

echo "Configuring ssh"
mkdir -p /root/.ssh
[ -f /root/.ssh/authorized_keys ] || echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNEtpAq3cp8kpMY8gmpVgt/EnzfF54OrEcWrDUDmoItTglvAoToW3AiL5Q8r9LjYUTaSRkGQADrKv43WL+qgnC4+9z2WXVjLF6AzQw/HkdvNih/CZoiW5Oka8L1hbbp+UzhT69lKz2h1/XDu0HLMQYu7IJqCNDUek09KSPVBRtpMhWOcEmHnJCOemcr494m0mTbVIs9uI6hSsnfkj6CoMS+ANFuwKJQtO/cLLpAHQmApto6Tu29P3zMKG2UMYLj8RkTVmhPUhCt4p3eXMICoya2sSeDjaRikGuTP4JR+reymtF6bcB3eOLbNo7LEJ3caaFt+HrHeX9AiX475FfSyHT eloyesp@cobre
" >> /root/.ssh/authorized_keys
chmod 600 /root/.ssh/authorized_keys

echo "Disable password login with ssh"
augtool -s "set /files/etc/ssh/sshd_config/PasswordAuthentication no"
service ssh reload

read -r -p "Application name: " application_name

echo "Creating the user for the application"
[ -d /home/$application_name ] || adduser $application_name --disabled-password

echo "Configuring ssh for $application_name"
mkdir -p /home/$application_name/.ssh
[ -f /home/$application_name/.ssh/authorized_keys ] || echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNEtpAq3cp8kpMY8gmpVgt/EnzfF54OrEcWrDUDmoItTglvAoToW3AiL5Q8r9LjYUTaSRkGQADrKv43WL+qgnC4+9z2WXVjLF6AzQw/HkdvNih/CZoiW5Oka8L1hbbp+UzhT69lKz2h1/XDu0HLMQYu7IJqCNDUek09KSPVBRtpMhWOcEmHnJCOemcr494m0mTbVIs9uI6hSsnfkj6CoMS+ANFuwKJQtO/cLLpAHQmApto6Tu29P3zMKG2UMYLj8RkTVmhPUhCt4p3eXMICoya2sSeDjaRikGuTP4JR+reymtF6bcB3eOLbNo7LEJ3caaFt+HrHeX9AiX475FfSyHT eloyesp@cobre
" >> /home/$application_name/.ssh/authorized_keys
chmod 600 /home/$application_name/.ssh/authorized_keys
chown $application_name:$application_name /home/$application_name/.ssh/authorized_keys

echo "Setup deploy folder"
mkdir -p /var/www/$application_name
chown $application_name:$application_name /var/www/$application_name
